apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploresg-fleet-service
  labels:
    app: exploresg-fleet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exploresg-fleet-service
  template:
    metadata:
      labels:
        app: exploresg-fleet-service
    spec:
      containers:
        - name: exploresg-fleet-service
          image: your-registry/exploresg-fleet-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: exploresg-config
            - secretRef:
                name: exploresg-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: exploresg-fleet-service
spec:
  selector:
    app: exploresg-fleet-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
